# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QCPointFiller
                                 A QGIS plugin
 Tool to automate the filling of fields in the QC shapefile and calculate the percentage accuracy
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-11-13
        git sha              : $Format:%H$
        copyright            : (C) 2019 by David Kerr
        email                : dk@tcarta.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from pathlib import Path
import pandas as pd

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, QgsVectorLayer, QgsVectorLayerJoinInfo, QgsProject, QgsExpression, Qgis, QgsField, NULL
from PyQt5.QtWidgets import QAbstractItemView, QAction, QMessageBox
from PyQt5.QtCore import QVariant

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .qc_point_filler_dialog import QCPointFillerDialog
import os.path

BASE_DIR = Path(__file__).resolve().parent
CSV = BASE_DIR.joinpath('csv/classes.csv')
CSV_POINTS = BASE_DIR.joinpath('csv/classes_for_points.csv')
CSV_AREAS = BASE_DIR.joinpath('csv/hatitat_tile_intersection_areas.csv')



class QCPointFiller:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QCPointFiller_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QC Point Field Filler')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QCPointFiller', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/qc_point_filler/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'QC Filler'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&QC Point Field Filler'),
                action)
            self.iface.removeToolBarIcon(action)

    def check_if_file_is_points(self, layer):
        points = True
        if not layer.geometryType() == 0:
            points = False
        return points

    def fill_fields(self, layer, name):
        """Join shapefile to csv and fill in the missing fields based on sub ID"""
        try:
            infoLyr = QgsVectorLayer(f'file:///{str(CSV)}?delimiter=,','classes', 'delimitedtext')
            QgsProject.instance().addMapLayer(infoLyr)
            csv_field = 'Int_SubNum'
            shp_field = 'QC_subnum'
            joinObject = QgsVectorLayerJoinInfo()
            joinObject.setJoinFieldName(csv_field)
            joinObject.setTargetFieldName(shp_field)
            joinObject.setJoinLayerId(infoLyr.id())
            joinObject.setUsingMemoryCache(True)
            joinObject.setJoinLayer(infoLyr)
            layer.addJoin(joinObject)
            layer.startEditing()
            for feature in layer.getFeatures():
                shp_fields = ['QC_num', 'QC_name', 'QC_subname']
                csv_fields = ['classes_Int_num', 'classes_Int_cls', 'classes_Int_SubCls']
                for shp, csv in zip(shp_fields, csv_fields):
                    f = layer.fields().indexFromName(csv)
                    f_ = layer.fields().indexFromName(shp)
                    layer.changeAttributeValue(feature.id(), f_, feature[f])
                qc_by = layer.fields().indexFromName('QC_by')
                layer.changeAttributeValue(feature.id(), qc_by, name)
        except KeyError as e:
            print(f'There is an incorrect value in the sub-class field in ID {feature.id()}', e)
        finally:
            error_id = []
            layer.removeJoin(infoLyr.id())
            QgsProject.instance().removeMapLayer(infoLyr)
            layer.commitChanges()
            for feature in layer.getFeatures():
                shp_field = 'QC_num'
                f_ = layer.fields().indexFromName(shp_field)
                if feature[f_] == NULL:
                    print(feature[f_])
                    print(f'Incorrect sub-class ID in: {feature.id()}')
                    error_id.append(feature.id())

            if error_id:
                QMessageBox.critical(self.iface.mainWindow(),
                            'Error with Sub-class ID!',
                            f"There seems to be incorrect subclass numeric ID s in the following IDs: {error_id}. Please double-check these?")

    def calculate_statistics(self, layer, folder):
        """Creates a csv of accuracy percentage between QC and Interpretation"""
        accuracy_csv = folder.joinpath(f'{layer.name()}_accuracy.csv')
        df_dict = {'ORTHOID': [], 'First_run_accuracy%': []}
        int_field = 'Hab_subnum'
        qc_field = 'QC_subnum'
        orthoid = ('_').join(layer.name().split('_')[:3])
        int_ = layer.fields().indexFromName(int_field)
        qc = layer.fields().indexFromName(qc_field)
        matching_values_counter = 0
        no_rows = layer.featureCount()
        for feature in layer.getFeatures():
            if feature[int_] == feature[qc]:
                matching_values_counter += 1
        accuracy = (matching_values_counter/no_rows) * 100
        df_dict['ORTHOID'].append(orthoid)
        df_dict['First_run_accuracy%'].append(accuracy)
        df_accuracy = pd.DataFrame(data=df_dict)
        df_accuracy.to_csv(accuracy_csv, index=False)
        return accuracy

    def fill_fields_and_calc_stats(self, layer, name):
        filename = Path(layer.source().split('|')[0]).resolve()
        if filename.exists():
            folder = filename.parent
            if self.check_if_file_is_points(layer):
                self.fill_fields(layer, name)
                accuracy = self.calculate_statistics(layer, folder)
                QMessageBox.information(self.iface.mainWindow(),
                                'Success',
                                f"Point shapefile saved successfully. Interpretation accuracy - {accuracy}%")   
            #Not a point file error
            else:
                QMessageBox.critical(self.iface.mainWindow(),
                                'Error! Not point file',
                                "Please choose a shapefile before continuing. This should be amended the tool rerun as it will affect the accuracy statistics.")
                raise IOError('Please input point file type')
        else:
            QMessageBox.critical(self.iface.mainWindow(),
                            f'Error! Layer {layer.name()} not saved',
                            "Please save the selected layer before continuing.")
            


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = QCPointFillerDialog()

         # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        # Populate the comboBox with names of all the loaded layers
        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        # show the dialog
        self.dlg.lineEdit.clear()
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            selected_layer_index = self.dlg.comboBox.currentIndex()
            selected_layer = layers[selected_layer_index].layer()
            name = self.dlg.lineEdit.text()
            self.fill_fields_and_calc_stats(selected_layer, name)